Watching for file changes with StatReloader
Internal Server Error: /upload_image/
Internal Server Error: /upload_image/
Internal Server Error: /upload_image/
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Memulai upload gambar
Tidak ada file yang diupload
Bad Request: /upload_image/
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\cindy\OneDrive\Desktop\Tugas Akhir\Code\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /generator/external
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 169, in external
    URLEdit, UrutanLidi = Image.imageOdd()
                          ^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 276, in imageOdd
    world = pants.World(comb, SkorACO)
            ^^^^^
NameError: name 'pants' is not defined
Not Found: /favicon.ico
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /generator/external
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 169, in external
    URLEdit, UrutanLidi = Image.imageOdd()
                          ^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 115, in imageOdd
    return self._generate_image(is_even=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 175, in _generate_image
    graph = {edge: SkorACO(*edge) for edge in comb}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 175, in <dictcomp>
    graph = {edge: SkorACO(*edge) for edge in comb}
                   ^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 119, in SkorACO
    temp1 = Array_data[a[0]]
                       ~^^^
TypeError: 'int' object is not subscriptable
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /generator/external
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 169, in external
    URLEdit, UrutanLidi = Image.imageOdd()
                          ^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 115, in imageOdd
    return self._generate_image(is_even=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 177, in _generate_image
    graph = {edge: SkorACO(*edge) for edge in comb}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 177, in <dictcomp>
    graph = {edge: SkorACO(*edge) for edge in comb}
                   ^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 120, in SkorACO
    raise ValueError(f"Expected tuples, got a={a}, b={b}")
ValueError: Expected tuples, got a=0, b=1
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /download/
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 275, in download
    return render(request, 'download.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in _init_
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 93: 'endif'. Did you forget to register or load this tag?
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /download/
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 275, in download
    return render(request, 'download.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in _init_
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 93: 'endif'. Did you forget to register or load this tag?
Internal Server Error: /list
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 379, in show
    return render(request, "ListMotif.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list' not found. 'list' is not a valid view function or pattern name.
Internal Server Error: /list
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 379, in show
    return render(request, "ListMotif.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list1' with arguments '(95,)' not found. 1 pattern(s) tried: ['list\\Z']
Internal Server Error: /download/
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 275, in download
    return render(request, 'download.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in _init_
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 93: 'endif'. Did you forget to register or load this tag?
Internal Server Error: /download/
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 275, in download
    return render(request, 'download.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in _init_
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 93: 'endif'. Did you forget to register or load this tag?
Watching for file changes with StatReloader
Internal Server Error: /list
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 379, in show
    return render(request, "ListMotif.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'list' not found. 'list' is not a valid view function or pattern name.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /generator/external
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 170, in external
    UrutanLidiRaw = Image.getUrutanLidiRaw()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 274, in getUrutanLidiRaw
    img_data, Lidi = ConvertRGB(img, Lidi, height, Direktori)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\ProcessImage.py", line 26, in ConvertRGB
    img.append(datas)
    ^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'append'
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\ProcessImage.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\ProcessImage.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /generator/external
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 170, in external
    Image = CreateImageMotif(str(fileurl), str(filename), str(jmlBaris), Baris, "4", username)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CreateImageMotif() takes no arguments
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /download/['slice_1.jpg', 'slice_2.jpg', 'slice_3.jpg', 'slice_4.jpg', 'slice_5.jpg', 'slice_6.jpg', 'slice_7.jpg', 'slice_8.jpg']
Internal Server Error: /gabungkan_motif/
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 907, in gabungkan_motif
    raw_lidi = request.session.get['raw_lidi']
              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'method' object is not subscriptable
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /generator/external
Traceback (most recent call last):
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py", line 174, in external
    UrutanLidiRaw, UrutanLidiIndex = Image.imageOriginal()
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py", line 65, in imageOriginal
    success = cv2.imwrite(slice_path, slice_img)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:836: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'

C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /list/motif_awal/slices/slice_4_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_6_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_3_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_1_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_2_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_5_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_8_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_7_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_1_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_1_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_2_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_3_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_7_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_5_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_4_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_8_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_6_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_1_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_2_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_7_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_5_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_3_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_4_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_6_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_8_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /list/motif_awal/slices/slice_3_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_1_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_6_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_2_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_4_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_5_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_8_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_7_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_2_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_1_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_3_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_4_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_5_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_6_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_7_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_8_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_1_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg/motif_awal
Not Found: /list/motif_awal/slices/slice_1_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_2_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_4_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_7_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_5_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_3_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_8_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
Not Found: /list/motif_awal/slices/slice_6_session_c65e779b-5bda-42a8-afd9-b5be84b2567b.jpg
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /motif_awal/slices/slice_1_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_3_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_5_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_2_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_6_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_4_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_8_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_7_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_1_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Watching for file changes with StatReloader
Not Found: /motif_awal/slices/slice_3_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_1_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_6_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_2_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_5_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_4_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_7_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_awal/slices/slice_8_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\1652\Downloads\AutoGenerateMotif\AutoGenerateMotif\Website\CreateImageModule.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /motif_awal/slices/slice_3_session_5a098b4d-46aa-4227-8625-a9cdc010cd08.jpg
Not Found: /motif_aw